[project]
name = "digitaldiscos-website"
version = "0.1.0"
description = "Frontend pÃºblico de Digital Discos"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "gunicorn>=23.0.0",
]
